astra_db:
  collection_name: "ecommercedata"

embedding_model:
  provider: "google"
  model_name: "models/text-embedding-004"

retriever:
  top_k: 10

llm:
  groq:
    provider: "groq"
    model_name: "llama-3.3-70b-versatile"
    temperature: 0
    max_output_tokens: 2048

  google:
    provider: "google"
    model_name: "gemini-2.0-flash"
    temperature: 0
    max_output_tokens: 2048

  openai:
    provider: "openai"
    model_name: "gpt-4"
    temperature: 0
    max_output_tokens: 2048

  huggingface:
    provider: "huggingface"
    model_name: "mistralai/Mistral-7B-Instruct-v0.2"
    temperature: 0.7
    max_output_tokens: 2048
